services:
  backend:
    build: .
    container_name: toro_toro_backend
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgis/postgis:16-3.4
    container_name: toro_toro_psql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toro_toro_psql
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
